#!/usr/bin/env python3

#   Rocket
#
#   Joe Gibson (gibsjose@mail.gvsu.edu)
#
#   17 August 2015
#
#   http://gibsjose.com
#   http://github.com/gibsjose/Rocket

# Essentials
from enum import Enum
from glob import glob
import sys, os, traceback, optparse
import re
import operator
import time
import datetime
import tempfile
import stat

# JSON and Pretty Print
import json
from pprint import pprint

# File Copying, `which()`, etc.
import shutil

# Call shell commands for `git`
from subprocess import call

class Language(Enum):
    """
    Defines the available languages as enumerated types
    """
    unknown = 0
    c = 1
    cpp = 2
    avr_c = 3
    avr_cpp = 4
    python = 5

# Global language dictionary
LanguageDictionary = {
    'c': Language.c,
    'cpp': Language.cpp,
    'c++': Language.cpp,
    'avr-c': Language.avr_c,
    'avr-cpp': Language.avr_cpp,
    'avr-c++': Language.avr_cpp,
    'python': Language.python
}

# Matches language names with their template directory name
LanguageNameDictionary = {
    'c': 'c',
    'cpp': 'cpp',
    'c++': 'cpp',
    'avr-c': 'avr-c',
    'avr-cpp': 'avr-cpp',
    'avr-c++': 'avr-cpp',
    'python': 'python'
}

class LanguageConfiguration:
    """
    Language Configuration from a `language.json` file
    """
    def __init__(self):
        """
        Default constructor
        """
        self.data = {}
        self.exists = False
        self.naming = None
        self.sources = []
        self.extension = True

    def Decode(self, filepath):
        """
        Try to read in and parse language config file
        """
        if os.path.exists(filepath):
            self.exists = True

            # Read language JSON data
            with open(filepath, encoding='utf-8') as lang_file:
                # Load JSON data
                self.data = json.loads(lang_file.read())

                # Naming
                if 'naming' in self.data:
                    self.naming = self.data['naming'].replace(' ', '-').lower()
                else:
                    self.naming = None

                # Sources
                if 'sources' in self.data:
                    self.sources = self.data['sources']
                else:
                    self.sources = []

                # extension
                if 'extension' in self.data:
                    self.extension = self.data['extension']
                else:
                    self.extension = True

        else:
            self.exists = False
            self.naming = None
            self.sources = []
            self.extension = True

class Configuration:
    def __init__(self):
        """
        Default constructor
        """
        self.data = {}

    def Modify(self, in_file, out_file, language_string):
        """
        Read in the JSON `in_file`, modify the language attribute, and write it out as the JSON `out_file`
        """
        # Check if config file exists
        if not os.path.exists(in_file):
            raise Exception('Configuration file does not exist at ' + in_file)

        with open(in_file, encoding='utf-8') as in_fp:
            # Load JSON data
            self.data = json.loads(in_fp.read())

            # Modify language string
            self.data["language"] = language_string

        with open(out_file, 'w', encoding='utf-8') as out_fp:
            # Write JSON data
            json.dump(self.data, out_fp, sort_keys=True, indent=4)

    def Encode(self, filepath):
        """
        Encode the configuration data as a JSON file
        """
        with open(filepath, 'w', encoding='utf-8') as config_file:
            json.dump(self.data, config_file, sort_keys=True, indent=4)

    def Decode(self, filepath):
        """
        Decode the configuration file as a Python JSON object (dictionary)
        """
        # Get current date in `DD MONTH YYYY` format
        today = datetime.date.today()
        self.date = today.strftime('%d %b %Y')

        # Check if config file exists
        if not os.path.exists(filepath):
            raise Exception('Configuration file does not exist at ' + filepath)

        # Read config JSON data
        with open(filepath, encoding='utf-8') as config_file:
            # Load JSON data
            self.data = json.loads(config_file.read())

            # Language (string)
            if 'language' not in self.data:
                raise Exception('Must specify \'language\' in config file')

            self.language_string = self.data['language']

            # Language (enum)
            lang = self.language_string.lower()
            if lang in LanguageDictionary:
                self.language = LanguageDictionary[lang]
            else:
                self.language = Language.unknown
                raise Exception('Unknown language')

            # Language (official name)
            self.language_name = LanguageNameDictionary[self.language_string]

            # Project name
            if 'project' not in self.data:
                raise Exception('Must specify \'project\' in config file')
            self.project = self.data['project']

            # Authors
            if 'authors' not in self.data:
                raise Exception('Must specify at least one author under \'authors\' in config file')
            self.authors = self.data['authors']

            for author in self.authors:
                if 'name' not in author:
                    raise Exception('Authors must have \'name\' attribute')

            # Websites
            if 'websites' in self.data:
                self.websites = self.data['websites']
            else:
                self.website = []

            # License
            if 'license' in self.data:
                self.license = self.data['license']
            else:
                self.license = 'None'

            # Git
            if 'git' in self.data:
                self.git = self.data['git']
            else:
                self.git = False

            # GitHub
            if 'github create' in self.data:
                self.github_create = self.data['github create']
            else:
                self.github_create = False

            if 'github remote' in self.data:
                self.github_remote = self.data['github remote']
            else:
                self.github_remote = 'None'

            if 'github user' in self.data:
                self.github_user = self.data['github user']
            else:
                self.github_user = 'None'

    def Print(self):
        print('Project: ' + self.project)
        print('Language: ' + self.language_string)
        print('Date: ' + self.date)
        print('License: ' + self.license)
        print('Author(s):')
        for author in self.authors:
            print('\t' + author['name'], end='')
            if 'email' in author:
                print(': ' + author['email'])
            else:
                print('')
        print('Website(s):')
        if len(self.websites) == 0:
            print('\t None')
        else:
            for website in self.websites:
                print('\t' + website)
        print('Git: ' + str(self.git))
        print('Create GitHub Repo: ' + str(self.github_create))
        print('GitHub Remote: ' + self.github_remote)
        print('GitHub User: ' + self.github_user)

class CommentFiller:
    """
    Replaces comment blocks in files with the appropriate data
    """
    def __init__(self, configuration):
        """
        Sets configuration values
        """
        self.configuration = configuration

    def Replace(self, files):
        """
        Intelligently replace comments in files based on language type
        """
        self.files = files

        for f in self.files:
            self.ReplaceInFile(f)

    def ReplaceInFile(self, filepath):
        """
        Replace the comment tags with actual data in a source file
        """
        if not os.path.exists(filepath):
            raise Exception('Cannot modify \'' + filepath + '\': Does not exist')

        #Create temp file
        fh, abs_path = tempfile.mkstemp()
        with open(abs_path,'w') as new_file:
            with open(filepath) as old_file:
                # Get header file name
                for f in self.files:
                    regex = re.compile(r'^.+\.h$')
                    if regex.match(f):
                        header = os.path.basename(f)

                for line in old_file:
                    # {TITLE}
                    if '{TITLE}' in line:
                        new_file.write(line.replace('{TITLE}', self.configuration.project))

                    # {AUTHORS}
                    elif '{AUTHORS}' in line:
                        first_author = self.configuration.authors[0]
                        auth = first_author['name'];
                        if 'email' in first_author:
                            auth += ' (' + first_author['email'] + ')'

                        new_file.write(line.replace('{AUTHORS}', auth))

                        if len(self.configuration.authors) > 1:
                            auth_iter = iter(self.configuration.authors)
                            next(auth_iter)
                            for author in auth_iter:
                                auth = author['name']
                                if 'email' in author:
                                    auth += ' (' + author['email'] + ')'

                                if self.configuration.language == Language.python:
                                    new_file.write('#\t' + auth + '\n')
                                else:
                                    new_file.write('*\t' + auth + '\n')

                    # {DD MONTH YYYY}
                    elif '{DD MONTH YYYY}' in line:
                        new_file.write(line.replace('{DD MONTH YYYY}', self.configuration.date))

                    # {WEBSITES}
                    elif '{WEBSITES}' in line:
                        if len(self.configuration.websites) > 0:
                            new_file.write(line.replace('{WEBSITES}', self.configuration.websites[0]))

                            webs_iter = iter(self.configuration.websites)
                            next(webs_iter)
                            for website in webs_iter:
                                if self.configuration.language == Language.python:
                                    new_file.write('#\t' + website + '\n')
                                else:
                                    new_file.write('*\t' + website + '\n')

                    # Header guards
                    elif '{GUARD}' in line:
                        guard = self.configuration.project.replace(' ', '_').upper() + '_H'
                        new_file.write(line.replace('{GUARD}', guard))

                    # Includes
                    elif '{HEADER}' in line:
                        new_file.write(line.replace('{HEADER}', header))

                    else:
                        new_file.write(line)

        # Close file
        os.close(fh)

        #Remove original file
        os.remove(filepath)

        #Move new file
        shutil.move(abs_path, filepath)

        print('\t> Updated ' + os.path.basename(filepath))

class MakefileFiller:
    """
    Replaces items in makefiles with appropriate data
    """
    def __init__(self, configuration):
        """
        Sets configuration values
        """
        self.configuration = configuration

    def Replace(self, filepath, binary):
        """
        Replace the makefile variables with actual data
        """
        if self.configuration.language == Language.python:
            return

        if not os.path.exists(filepath):
            raise Exception('Cannot modify \'' + filepath + '\': Does not exist')

        #Create temp file
        fh, abs_path = tempfile.mkstemp()
        with open(abs_path,'w') as new_file:
            with open(filepath) as old_file:
                for line in old_file:
                    # {BIN}
                    if '{BIN}' in line:
                        new_file.write(line.replace('{BIN}', binary))

                    else:
                        new_file.write(line)

        # Close file
        os.close(fh)

        #Remove original file
        os.remove(filepath)

        #Move new file
        shutil.move(abs_path, filepath)

        print('\t> Updated ' + os.path.basename(filepath))


class FileNamer:
    """
    Renames files with appropriate name
    """
    def __init__(self, configuration):
        """
        Sets configuration values and parses language config, if it exists
        """
        self.configuration = configuration

        self.rocket_directory = os.path.dirname(os.path.realpath(sys.argv[0]))
        language_file = self.rocket_directory + '/languages/' + self.configuration.language_name + '/language.json'

        self.language_configuration = LanguageConfiguration()
        self.language_configuration.Decode(language_file)

    def SpacesToUnderscores(self, word):
        """
        Converts spaces to lowercase underscores: 'Rocket Project' -> 'rocket_project'
        """
        return word.replace(' ', '_').lower()

    def SpacesToDashes(self, word):
        """
        Converts spaces to lowercase dashes: 'Rocket Project' -> 'rocket-project'
        """
        return word.replace(' ', '-').lower()

    def UnderscoresToCamelCase(self, word):
        """
        Converts lowercase underscores to CamelCase: 'rocket_project' -> 'RocketProject'
        """
        return ''.join(x.capitalize() or '_' for x in word.split('_'))

    def SpacesToCamelCase(self, word):
        """
        Converts spaces to CamelCase: 'Rocket Project' -> 'RocketProject'
        """
        return self.UnderscoresToCamelCase(self.SpacesToUnderscores(word))

    def GenerateName(self):
        """
        Generates a name for a file based on the project name and language type
        """
        # First try to pull from the $(ROCKET_DIR)/languages/*/language.json file
        if self.language_configuration.exists:
            # Naming options:
            #   'dashes' or 'dash': 'Rocket Project' -> 'rocket-project'
            #   'underscores' or 'underscore': 'Rocket Project' -> 'rocket_project'
            #   'camel-case' or 'camelcase' or 'camel_case': 'Rocket Project' -> 'RocketProject'
            naming = self.language_configuration.naming
            print('\t> Using naming: ' + naming)

            if naming == 'dashes' or naming == 'dash':
                self.name = self.SpacesToDashes(self.configuration.project)
                return

            elif naming == 'underscores' or naming == 'underscore':
                self.name = self.SpacesToUnderscores(self.configuration.project)
                return

            elif naming == 'camel-case' or naming == 'camelcase' or naming == 'camel_case':
                self.name = self.SpacesToCamelCase(self.configuration.project)
                return

            # If 'naming' attribute unrecognized, just break and use defaults below
            else:
                None;

        # Otherwise use defaults
        language = self.configuration.language

        # 'Rocket Project' -> 'rocket-project' for C
        if language == Language.c or language == Language.avr_c:
            self.name =  self.SpacesToDashes(self.configuration.project)
            print('\t> Defaulting to \'dashes\' naming for ' + self.configuration.language_string + ' projects')

        # 'Rocket Project' -> 'RocketProject' for C++
        elif language == Language.cpp or language == Language.avr_cpp:
            self.name = self.SpacesToCamelCase(self.configuration.project)
            print('\t> Defaulting to \'camel-case\' naming for ' + self.configuration.language_string + ' projects')

        # 'Rocket Project' -> 'rocket_project' for Python
        elif language == Language.python:
            self.name =  self.SpacesToUnderscores(self.configuration.project)
            print('\t> Defaulting to \'underscores\' naming for ' + self.configuration.language_string + ' projects')

        # 'Rocket Project' -> 'rocket_project' for all else
        else:
            self.name = self.SpacesToUnderscores(self.configuration.project)
            print('\t> Defaulting to \'underscores\' naming for ' + self.configuration.language_string + ' projects')

        return

    def Rename(self):
        """
        Rename the files according to the project name
        """
        # Generate a name
        self.GenerateName()
        print('\t> Name generated: ' + self.name)

        # Create file list
        self.files = []
        language = self.configuration.language
        sources = self.language_configuration.sources

        directory = os.getcwd()

        if language == Language.python:
            src_directory = directory + '/'
        else:
            src_directory = directory + '/src/'

        for f in os.listdir(src_directory):
            for s in sources:
                if f.endswith(s):
                    self.files.append(src_directory + f)

        print('\t> Renaming the following files:')
        for f in self.files:
            print('\t\t* ' + os.path.basename(f))

        # Rename all files
        self.renamed = []
        for f in self.files:
            self.renamed.append(self.RenameFile(f))

        print('\t> to:')
        for f in self.renamed:
            print('\t\t* ' + os.path.basename(f))

        return self.renamed

    def RenameFile(self, filepath):
        """
        Rename an individual file according to the project name
        """
        new_name = filepath.replace('rocket', self.name)

        if not self.language_configuration.extension:
            for s in self.language_configuration.sources:
                new_name.replace(s, '')

        os.rename(filepath, new_name)

        return new_name

class Rocket:
    """
    Defines the Rocket object for creating project/code templates
    """
    def __init__(self):
        """
        Rocket default constructor
        """
        self.language = Language.unknown

    def Generate(self, language):
        """
        Generates the skeleton code, makefiles (if necessary), gitignore
        files, etc. and generates a default `config.json` object with the correct language
        """
        # Set language
        # - 'language' is the user's raw input
        # - 'lang' is a lowercase version of 'language'
        # - 'self.language' is the actual language type enum (e.g. Language.cpp)
        # - 'language_name' is the accepted language name by Rocket (e.g. 'C++' turn to 'cpp')
        lang = language.lower()
        if lang in LanguageDictionary:
            self.language = LanguageDictionary[lang]
            language_name = LanguageNameDictionary[lang]
        else:
            self.language = Language.unknown
            language_name = 'unknown'
            raise Exception('Unknown language')

        rocket_directory = os.path.dirname(os.path.realpath(sys.argv[0]))
        print('\t> Copying from Rocket directory: ' + rocket_directory)

        # Pull correct files and copy them to local directory
        directory = os.getcwd()
        print('\t> Current directory: ' + directory)

        # Write a default `config.json` file with the correct language
        # Read in the default file, change the language attribute, and write it
        self.configuration = Configuration()
        self.configuration.Modify(rocket_directory + '/config.json', directory + '/config.json', language_name)
        print('\t> Created default ' + language + ' configuration file \'./config.json\'')

        # @TODO Make this more modular by using the language's 'language.json' file and a LanguageConfiguration object
        # Make directories and copy files as needed for specific languages
        if (self.language == Language.c) or (self.language == Language.cpp) or (self.language == Language.avr_c) or (self.language == Language.avr_cpp):
            # Create necessary directories
            if not os.path.exists(directory + '/src/'):
                os.makedirs(directory + '/src/')
                print('\t> Created source directory \'./src/\'')

            # Copy the skeleton code
            if (self.language == Language.c) or (self.language == Language.avr_c):
                shutil.copy(rocket_directory + '/languages/' + language_name + '/skeleton/rocket.c', directory + '/src/')
                shutil.copy(rocket_directory + '/languages/' + language_name + '/skeleton/rocket.h', directory + '/src/')
                print('\t> Created skeleton \'.c\' and \'.h\' files in \'./src/\'')
            else:
                shutil.copy(rocket_directory + '/languages/' + language_name + '/skeleton/rocket.cpp', directory + '/src/')
                shutil.copy(rocket_directory + '/languages/' + language_name + '/skeleton/rocket.h', directory + '/src/')
                print('\t> Created skeleton \'.cpp\' and \'.h\' files in \'./src/\'')

            # Copy the makefile
            shutil.copy(rocket_directory + '/languages/' + language_name + '/makefile', directory)
            print('\t> Created ' + language + ' \'./makefile\'')

        elif self.language == Language.python:
            shutil.copy(rocket_directory + '/languages/' + language_name + '/skeleton/rocket.py', directory)
            print('\t> Created skeleton \'.py\' file')

    def Config(self):
        """
        Pull from the generated and (maybe) edited `config.json` file, and
        make changes to comment header blocks
        """
        # Create a configuration object
        self.configuration = Configuration()

        # Decode the configuration object
        self.configuration.Decode(os.getcwd() + '/config.json')

        if self.configuration.language_string in LanguageNameDictionary:
            language_name = LanguageNameDictionary[self.configuration.language_string]
        else:
            language_name = 'unknown'

        print('\t> Generated date: ' + self.configuration.date)
        print('\t> Detected language: ' + self.configuration.language_string)
        print('\t> Detected project name: ' + self.configuration.project)

        # Modify skeleton files/makefiles with data from `config.json`
        rocket_directory = os.path.dirname(os.path.realpath(sys.argv[0]))
        directory = os.getcwd()

        # Rename skeleton code files to project name
        file_namer = FileNamer(self.configuration)
        files = file_namer.Rename()

        # Modify skeleton code (and makefile if necessary)
        comment_filler = CommentFiller(self.configuration)
        comment_filler.Replace(files)

        makefile_filler = MakefileFiller(self.configuration)
        makefile_filler.Replace(directory + '/makefile', file_namer.name)

        # Re-apply executable privilages for Python scripts
        if self.configuration.language == Language.python:
            for f in files:
                os.chmod(f, stat.S_IRWXU)

        # If project will be a `git` repo add `.gitignore` and `README.md`
        if self.configuration.git:
            # Create README
            with open(directory + '/README.md', 'w') as readme:
                readme.write('# ' + self.configuration.project + '\n')
                readme.write(self.configuration.date + '\n')

            # Copy the `.gitignore`
            shutil.copy(rocket_directory + '/languages/' + language_name + '/' + language_name + '.gitignore', directory + '/.gitignore')
            print('\tCreated ' + self.configuration.language_string + ' \'./.gitignore\'')

            # Run `git init`
            call("git init", shell=True)

        # # @TODO
        # # If project includes a GitHub account, either add or create remote
        # if self.configuration.github_create:
        #     # Create GitHub account using `hub`, if installed

    def Clear(self):
        """
        Remove generated project files in the current directory
        """
        rocket_directory = os.path.dirname(os.path.realpath(sys.argv[0]))
        directory = os.getcwd()

        # Make sure user knows exactly which directory they are in
        response = input('Remove all project files in \'' + directory + '\'? [Y/n]: ')
        if not response == 'Y':
            return 1

        # Have at least *some* sanity check...
        if directory == rocket_directory:
            raise Exception('Removing here would remove Rocket\'s files...')
        elif directory == '/':
            raise Exception('You do not really want to remove \'' + directory + '\', right...?')
        elif directory == '/usr':
            raise Exception('You do not really want to remove \'' + directory + '\', right...?')
        elif directory == os.path.expanduser('~'):
            raise Exception('You do not really want to remove \'' + directory + '\', right...?')

        # Can use the `config.json` to more intelligently remove files if it exists
        if os.path.exists(directory + '/config.json'):
            configuration = Configuration()
            configuration.Decode(directory + '/config.json')
            configuration.Print()

        # @TODO Add 'files' attribute to 'config.json' when generating as files are added and only use that! Do not do any blind removal

        # @TODO How to handle '.gitignore' and '.git/'?

        # Else do blind removal of *.py, config.json, makefile, .gitignore, ./.git/, ./src/, ./obj/, ./bin/, {Executable}, etc.
        # else:
        #     os.remove(glob(directory + '/*.py'))
        #     os.remove(directory + '/config.json')
        #     os.remove(directory + '/makefile')
        #     os.remove(directory + '/.gitignore')
        #     shutil.rmtree(directory + '/.git/')
        #     shutil.rmtree(directory + '/src/')
        #     shutil.rmtree(directory + '/obj/')
        #     shutil.rmtree(directory + '/bin/')

        return 0

    def Print(self):
        """
        Prints the configuration data in a nice format
        """
        self.configuration.Print()

def main():
    """
    Rocket main
    """
    global options, args

    print('-------')
    print('Rocket!')
    print('-------')

    # Make sure Rocket is not being executed in the install directory
    if os.getcwd() == os.path.dirname(os.path.realpath(sys.argv[0])):
        raise Exception('You do not want to execute \'rocket\' in it\'s own directory...')

    # Ask user to continue if the directory is not empty
    if os.listdir(os.getcwd()):
        if not input('You really should run \'rocket\' in an empty directory... Continue? [Y/n] ') == 'Y':
            return 0

    # Execute command
    if options.remove:
        directory = os.getcwd()
        print('\n>>> Removing existing project files >>>')
        rocket = Rocket()
        if not rocket.Clear():
            print('<<< Project files removed <<<')

    elif options.language:
        rocket = Rocket()
        print('\n>>> Generating a blank ' + options.language + ' project >>>')
        rocket.Generate(options.language)
        print('<<< Generated skeleton ' + options.language + ' project <<<')
        print('<<< Edit the \'./config.json\' file with your project settings and run \'rocket -c\' to finish <<<')

    elif options.config:
        rocket = Rocket()
        print('\n>>> Configuring the project >>>')
        rocket.Config()
        print('<<< Configured \'' + rocket.configuration.project + '\' <<<')

    else:
        raise Exception('Must specify language with \'-l LANGUAGE\' or run config with \'-c\' or \'--config\'')

if __name__ == '__main__':
    try:
        start_time = time.time()
        parser = optparse.OptionParser(formatter=optparse.TitledHelpFormatter(), usage=globals()['__doc__'], version='0.1.0')

        parser.add_option('-l', '--language', action='store', type='string', dest='language', help='language')

        parser.add_option('-c', '--config', action='store_true', default=False, help='Configure project using config.json file')

        parser.add_option('-r', '--remove', action='store_true', default=False, help='Remove all project files if they exist')

        parser.add_option('-v', '--verbose', action='store_true', default=False, help='verbose mode')

        (options, args) = parser.parse_args()

        main()
        if options.verbose: print('\n' + time.asctime())
        if options.verbose: print('Total Runtime: ', end='')
        if options.verbose: print(str((time.time() - start_time) * 1000) + ' ms')
        sys.exit(0)
    except KeyboardInterrupt as e: # Ctrl-C
        raise e
    except SystemExit as e: # sys.exit()
        raise e
    except Exception as e:
        print('\n<-- Exception: ', end='')
        print(str(e), end=' -->\n\n')
        if(options.verbose):
            traceback.print_exc()

        os._exit(1)
